version: '3'


services:
  postgis:
    image: postgis/postgis:12-3.0-alpine
    shm_size: 1gb
    volumes:
      - db-data:/var/lib/postgresql/data
      - .:/code
    ports:
      - "5432:5432"
    env_file: .env
  django:
    build: .
    shm_size: 1gb
    depends_on:
      - postgis
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=cbb.settings.base
#    command: "/usr/local/bin/gunicorn cbb.wsgi:application -w 2 -b 0.0.0.0:8000 -u root --pid /tmp/gunicorn.pid"
#    command: /usr/local/bin/python /code/manage.py runserver 0.0.0.0:8000
    env_file: .env
